import type { TimetableEntry, Announcement, QuickLink, SocietyEvent } from "@/types";

export const TIMETABLE: TimetableEntry[] = [
  {
    id: "t1",
    moduleCode: "CS1001",
    moduleName: "Introduction to Programming",
    lecturer: "Dr. Amara Osei",
    room: "G.14",
    building: "Kenwood Building",
    day: "Monday",
    startTime: "09:00",
    endTime: "10:00",
    type: "Lecture",
    colour: "#4F6EF7",
  },
  {
    id: "t2",
    moduleCode: "MATH1200",
    moduleName: "Calculus & Linear Algebra",
    lecturer: "Prof. Yuki Tanaka",
    room: "LT3",
    building: "Sciences Block",
    day: "Monday",
    startTime: "11:00",
    endTime: "12:00",
    type: "Lecture",
    colour: "#E07A5F",
  },
  {
    id: "t3",
    moduleCode: "CS1001",
    moduleName: "Introduction to Programming",
    lecturer: "Dr. Amara Osei",
    room: "Lab 2",
    building: "Kenwood Building",
    day: "Tuesday",
    startTime: "14:00",
    endTime: "16:00",
    type: "Lab",
    colour: "#4F6EF7",
  },
  {
    id: "t4",
    moduleCode: "ENG1050",
    moduleName: "Academic Writing & Communication",
    lecturer: "Ms. Fiona Blackwell",
    room: "H.07",
    building: "Humanities Hub",
    day: "Tuesday",
    startTime: "10:00",
    endTime: "11:00",
    type: "Seminar",
    colour: "#3DAB7E",
  },
  {
    id: "t5",
    moduleCode: "MATH1200",
    moduleName: "Calculus & Linear Algebra",
    lecturer: "Prof. Yuki Tanaka",
    room: "T.02",
    building: "Sciences Block",
    day: "Wednesday",
    startTime: "09:00",
    endTime: "10:00",
    type: "Tutorial",
    colour: "#E07A5F",
  },
  {
    id: "t6",
    moduleCode: "CS1010",
    moduleName: "Systems & Networks",
    lecturer: "Dr. Liam Ó Briain",
    room: "LT1",
    building: "Kenwood Building",
    day: "Wednesday",
    startTime: "13:00",
    endTime: "14:00",
    type: "Lecture",
    colour: "#9B59B6",
  },
  {
    id: "t7",
    moduleCode: "ENG1050",
    moduleName: "Academic Writing & Communication",
    lecturer: "Ms. Fiona Blackwell",
    room: "H.07",
    building: "Humanities Hub",
    day: "Thursday",
    startTime: "11:00",
    endTime: "12:00",
    type: "Lecture",
    colour: "#3DAB7E",
  },
  {
    id: "t8",
    moduleCode: "CS1010",
    moduleName: "Systems & Networks",
    lecturer: "Dr. Liam Ó Briain",
    room: "Lab 1",
    building: "Kenwood Building",
    day: "Thursday",
    startTime: "15:00",
    endTime: "17:00",
    type: "Lab",
    colour: "#9B59B6",
  },
  {
    id: "t9",
    moduleCode: "CS1001",
    moduleName: "Introduction to Programming",
    lecturer: "Dr. Amara Osei",
    room: "T.05",
    building: "Kenwood Building",
    day: "Friday",
    startTime: "10:00",
    endTime: "11:00",
    type: "Tutorial",
    colour: "#4F6EF7",
  },
  {
    id: "t10",
    moduleCode: "MATH1200",
    moduleName: "Calculus & Linear Algebra",
    lecturer: "Prof. Yuki Tanaka",
    room: "LT3",
    building: "Sciences Block",
    day: "Friday",
    startTime: "13:00",
    endTime: "14:00",
    type: "Lecture",
    colour: "#E07A5F",
  },
];

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: "a1",
    title: "Library induction sessions now open for booking",
    body: "All first-year students must complete the library induction before Week 3. Slots available via the student portal.",
    category: "Academic",
    date: "2025-09-16",
    urgent: false,
  },
  {
    id: "a2",
    title: "Campus Wi-Fi upgrade — brief outage Saturday 02:00–04:00",
    body: "IT Services will be performing essential maintenance. Plan offline work during this window.",
    category: "IT",
    date: "2025-09-17",
    urgent: true,
  },
  {
    id: "a3",
    title: "Freshers' Fair — Thursday, Courtyard Quad",
    body: "Over 80 student societies will be represented. Come find your community!",
    category: "Events",
    date: "2025-09-18",
    urgent: false,
  },
  {
    id: "a4",
    title: "Free mental health drop-in every Wednesday",
    body: "The Student Wellbeing Centre runs anonymous drop-in sessions 12:00–15:00 in Welfare House Room 3.",
    category: "Welfare",
    date: "2025-09-15",
    urgent: false,
  },
];

export const QUICK_LINKS: QuickLink[] = [
  {
    id: "ql1",
    label: "My Timetable",
    href: "/timetable",
    icon: "calendar",
    description: "View your weekly class schedule",
  },
  {
    id: "ql2",
    label: "Campus Map",
    href: "/map",
    icon: "map",
    description: "Find buildings and rooms",
  },
  {
    id: "ql3",
    label: "Library",
    href: "/library",
    icon: "book",
    description: "Search books and reserve study rooms",
  },
  {
    id: "ql4",
    label: "Student Email",
    href: "/email",
    icon: "mail",
    description: "Check your university inbox",
  },
  {
    id: "ql5",
    label: "Grades",
    href: "/grades",
    icon: "chart",
    description: "View submitted assignments and results",
  },
  {
    id: "ql6",
    label: "Wellbeing",
    href: "/wellbeing",
    icon: "heart",
    description: "Support services and resources",
  },
];

export const SOCIETY_EVENTS: SocietyEvent[] = [
  {
    id: "ev1",
    title: "AI & Ethics Panel Discussion",
    societyName: "Computer Science Society",
    category: "Tech",
    date: "2026-05-08",
    time: "18:00",
    location: "Kenwood Building, Lecture Theatre 1",
    description:
      "Join leading researchers and industry guests for a panel on the ethics of modern AI systems. Open Q&A and refreshments to follow.",
    tags: ["ai", "ethics", "panel"],
    featured: true,
  },
  {
    id: "ev2",
    title: "Spring Charcoal Workshop",
    societyName: "Fine Arts Society",
    category: "Arts & Culture",
    date: "2026-05-10",
    time: "14:00",
    location: "Humanities Hub, Studio 3",
    description:
      "A beginner-friendly charcoal sketching workshop. All materials provided. Limited to 15 students — bring a friend!",
    tags: ["sketching", "art", "workshop"],
    featured: true,
  },
  {
    id: "ev3",
    title: "Friday Five-a-Side Tournament",
    societyName: "Football Club",
    category: "Sports",
    date: "2026-05-09",
    time: "17:30",
    location: "Sports Centre, Pitch B",
    description:
      "Sign up solo or as a team of five. Prizes for winners. Supporters welcome on the sidelines.",
    tags: ["football", "tournament"],
  },
  {
    id: "ev4",
    title: "Volleyball Open Training",
    societyName: "Volleyball Club",
    category: "Sports",
    date: "2026-05-12",
    time: "19:00",
    location: "Sports Centre, Hall 2",
    description:
      "Open training session for all levels. New members especially welcome — come try it out, no commitment needed.",
    tags: ["volleyball", "beginners"],
  },
  {
    id: "ev5",
    title: "Photography Walk: Old Town",
    societyName: "Photography Society",
    category: "Hobbies",
    date: "2026-05-11",
    time: "11:00",
    location: "Meet at Main Library steps",
    description:
      "A guided photography walk through the old town. Bring any camera — phone, DSLR, film, anything goes.",
    tags: ["photography", "outdoors"],
  },
  {
    id: "ev6",
    title: "Maths Society Pub Quiz",
    societyName: "Mathematics Society",
    category: "Academic",
    date: "2026-05-14",
    time: "20:00",
    location: "Student Union Bar",
    description:
      "Our termly pub quiz returns. Maths-themed rounds, general knowledge, and prizes for the top three teams.",
    tags: ["quiz", "social"],
  },
  {
    id: "ev7",
    title: "Game Dev Showcase",
    societyName: "Game Development Society",
    category: "Tech",
    date: "2026-05-15",
    time: "16:00",
    location: "Sciences Block, Room 2.04",
    description:
      "Members demo games they've built this term. Drop in any time to play, vote for your favourite, and chat with the makers.",
    tags: ["games", "showcase"],
    featured: true,
  },
  {
    id: "ev8",
    title: "Wellness Yoga Hour",
    societyName: "Wellbeing Society",
    category: "Hobbies",
    date: "2026-05-13",
    time: "08:00",
    location: "Sports Centre, Studio 1",
    description:
      "Start your day with a gentle yoga session. Mats provided. Suitable for complete beginners.",
    tags: ["yoga", "wellbeing"],
  },
];